(()=>{
'use strict';
const L=window.DCMLogic, CFG=window.DCM_CONFIG, DATA_KEY='dcm-dashboard-v8-data', ACTION_KEY='dcm-dashboard-v10-actions';
const E=L.E, $=id=>document.getElementById(id);
const reasons={'01':'시스템 미구축','02':'거래처 사용거부','03':'ERP Interface 오류','04':'Master 불일치','05':'신규거래처','06':'공급중단 예정','07':'사용법 미숙','08':'데이터 오류','09':'확인 중','99':'기타'};
function clone(x){return JSON.parse(JSON.stringify(x));}
function loadData(){try{const x=JSON.parse(localStorage.getItem(DATA_KEY));if(Array.isArray(x))return x;}catch(e){}return clone(window.DCM_BASE_DATA||[]);}
function loadActions(){try{const x=JSON.parse(localStorage.getItem(ACTION_KEY));return Array.isArray(x)?x:[];}catch(e){return [];}}
let actions=loadActions();
function saveActions(){localStorage.setItem(ACTION_KEY,JSON.stringify(actions));}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function pct(v){return v==null?'—':(v*100).toFixed(1)+'%';} function pp(v){return v==null?'—':`${v>=0?'+':''}${(v*100).toFixed(1)}%p`;}
function key(r){return `${r.outlet}|||${r.businessNo}`;} function actionKey(outlet,biz){return `${outlet}|||${biz}`;}
function months(data){return [...new Set(data.map(r=>r.month))].sort();}
function selected(data,m){const manager=$('manager')?.value||'전체',outlet=$('outlet')?.value||'전체';return data.filter(r=>r.month===m&&(manager==='전체'||r.manager===manager)&&(outlet==='전체'||r.outlet===outlet));}
function streaks(data,cur){const ms=months(data).filter(m=>m<=cur), by=new Map();data.filter(r=>ms.includes(r.month)).forEach(r=>{const k=key(r);if(!by.has(k))by.set(k,{});by.get(k)[r.month]=r;});const out=[];by.forEach((hist,k)=>{const r=hist[cur];if(!r)return;const entityStreak={};let max=0;E.forEach(e=>{let n=0;for(let i=ms.length-1;i>=0;i--){const rr=hist[ms[i]],s=L.normStatus(rr?.statuses?.[e]);if(s==='X')n++;else break;}entityStreak[e]=n;max=Math.max(max,n);});out.push({...r,streak:max,entityStreak});});return out;}
function riskRows(data,cur,prev,curr,prior,ch){const st=streaks(data,cur), o2x=new Set(ch.oToX.map(x=>`${x.outlet}|||${x.businessNo}|||${x.entity}`)), pmap=new Map(prior.map(r=>[key(r),r]));return st.filter(r=>E.some(e=>L.normStatus(r.statuses?.[e])==='X')).map(r=>{let score=0,xCount=0,persist=0,degrade=0,newX=0;E.forEach(e=>{const s=L.normStatus(r.statuses?.[e]);if(s==='X'){xCount++;score+=2;if(r.entityStreak[e]>=2){persist++;score+=3*Math.min(r.entityStreak[e]-1,3);}if(o2x.has(`${r.outlet}|||${r.businessNo}|||${e}`)){degrade++;score+=4;}const ps=L.normStatus(pmap.get(key(r))?.statuses?.[e]);if(!ps){newX++;score+=2;}}});const priority=score>=12?'P1':score>=7?'P2':'P3';return {...r,xCount,score,persist,degrade,newX,priority};}).sort((a,b)=>b.score-a.score||b.xCount-a.xCount||a.businessName.localeCompare(b.businessName,'ko'));}
function actionFor(r){return actions.find(a=>a.key===actionKey(r.outlet,r.businessNo))||null;}
function actionStatusLabel(s){return ({TODO:'미조치',IN_PROGRESS:'진행중',WAITING:'업체회신',DONE:'완료'})[s]||'미조치';}
function render(){const data=loadData(),cur=$('month')?.value||months(data).at(-1);if(!cur)return;const ms=months(data),i=ms.indexOf(cur),prev=i>0?ms[i-1]:null,curr=selected(data,cur),prior=prev?selected(data,prev):[],s=L.summarize(curr),ps=L.summarize(prior),ch=L.compare(prior,curr),risks=riskRows(data,cur,prev,curr,prior,ch),persistent=risks.filter(r=>r.streak>=2),target=.90,gap=Math.max(0,target-(s.rate||0)),needImprove=s.evaluated?Math.ceil(Math.max(0,target*s.evaluated-s.O)):0;
$('ctRate').textContent=pct(s.rate);$('ctDelta').textContent=prev?pp(s.rate-ps.rate):'—';$('ctX').textContent=s.X.toLocaleString();$('ctX2O').textContent=ch.xToO.length.toLocaleString();$('ctO2X').textContent=ch.oToX.length.toLocaleString();$('ctPersist').textContent=persistent.reduce((n,r)=>n+E.filter(e=>r.entityStreak[e]>=2).length,0).toLocaleString();
const aging={m1:0,m2:0,m3:0,m46:0,m6:0};risks.forEach(r=>E.forEach(e=>{const n=r.entityStreak[e];if(!n)return;if(n===1)aging.m1++;else if(n===2)aging.m2++;else if(n===3)aging.m3++;else if(n<=6)aging.m46++;else aging.m6++;}));[['ctAge1',aging.m1],['ctAge2',aging.m2],['ctAge3',aging.m3],['ctAge46',aging.m46],['ctAge6',aging.m6]].forEach(([id,v])=>$(id).textContent=v.toLocaleString());
$('ctTargetNow').textContent=pct(s.rate);$('ctTargetGap').textContent=pp(-gap);$('ctTargetNeed').textContent=`${needImprove.toLocaleString()}건`;
$('ctRiskBody').innerHTML=risks.slice(0,20).map((r,idx)=>`<tr><td>${idx+1}</td><td><span class="ct-priority ct-${r.priority.toLowerCase()}">${r.priority}</span></td><td>${esc(r.outlet)}</td><td>${esc(r.manager)}</td><td>${esc(r.businessName)}</td><td class="mono">${esc(r.businessNo)}</td><td>${E.map(e=>L.normStatus(r.statuses[e])||'-').join(' / ')}</td><td>${r.streak}M</td><td><strong>${r.score}</strong></td><td><button class="ct-btn" data-open="${esc(r.outlet)}|||${esc(r.businessNo)}">Action</button></td></tr>`).join('')||'<tr><td colspan="10" class="empty">미연동 위험 거래처가 없습니다.</td></tr>';
const actionRows=risks.slice(0,30);$('ctActionBody').innerHTML=actionRows.map(r=>{const a=actionFor(r)||{};return `<tr><td><span class="ct-priority ct-${r.priority.toLowerCase()}">${r.priority}</span></td><td>${esc(r.businessName)}</td><td>${esc(r.outlet)}</td><td>${esc(r.manager)}</td><td>${r.streak}M</td><td><select data-field="reasonCode" data-key="${esc(actionKey(r.outlet,r.businessNo))}"><option value="">원인 선택</option>${Object.entries(reasons).map(([k,v])=>`<option value="${k}" ${a.reasonCode===k?'selected':''}>${k} ${v}</option>`).join('')}</select></td><td><input type="text" data-field="plan" data-key="${esc(actionKey(r.outlet,r.businessNo))}" value="${esc(a.plan||'')}" placeholder="조치계획"></td><td><input type="date" data-field="dueDate" data-key="${esc(actionKey(r.outlet,r.businessNo))}" value="${esc(a.dueDate||'')}"></td><td><select data-field="status" data-key="${esc(actionKey(r.outlet,r.businessNo))}">${['TODO','IN_PROGRESS','WAITING','DONE'].map(x=>`<option value="${x}" ${(a.status||'TODO')===x?'selected':''}>${actionStatusLabel(x)}</option>`).join('')}</select></td></tr>`}).join('');
const used={};actions.forEach(a=>{if(a.reasonCode)used[a.reasonCode]=(used[a.reasonCode]||0)+1;});const total=Object.values(used).reduce((a,b)=>a+b,0)||1;$('ctReasonBars').innerHTML=Object.entries(used).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,v])=>`<div class="ct-bar-row"><span>${esc(reasons[k]||k)}</span><div class="ct-bar"><i style="width:${v/total*100}%"></i></div><b>${v}</b></div>`).join('')||'<div class="ct-note">Action Board에서 원인코드를 입력하면 자동 집계됩니다.</div>';
const outlets=[...new Set(curr.map(r=>r.outlet))].map(o=>{const cs=L.summarize(curr.filter(r=>r.outlet===o)),prs=L.summarize(prior.filter(r=>r.outlet===o));return {o,rate:cs.rate,delta:prev&&prs.rate!=null&&cs.rate!=null?cs.rate-prs.rate:null,x:cs.X};}).sort((a,b)=>(a.rate??1)-(b.rate??1));const worst=outlets[0],mostX=[...outlets].sort((a,b)=>b.x-a.x)[0];const bestImp=[...outlets].filter(x=>x.delta!=null).sort((a,b)=>b.delta-a.delta)[0];
$('ctAi').innerHTML=`<strong>${cur} 월간 요약</strong><br>• 전체 연동률 <strong>${pct(s.rate)}</strong>${prev?`, 전월 대비 <strong>${pp(s.rate-ps.rate)}</strong>`:''}<br>• 미연동 X <strong>${s.X.toLocaleString()}건</strong>, X→O 개선 <strong>${ch.xToO.length.toLocaleString()}건</strong>, O→X 악화 <strong>${ch.oToX.length.toLocaleString()}건</strong><br>• ${mostX?`미연동 절대량 최다: <strong>${esc(mostX.o)} X ${mostX.x}</strong>`:'거점 데이터 없음'}<br>• ${worst?`연동률 최저: <strong>${esc(worst.o)} ${pct(worst.rate)}</strong>`:''}<br>• ${bestImp?`개선폭 최대: <strong>${esc(bestImp.o)} ${pp(bestImp.delta)}</strong>`:''}<br><br><strong>Recommended Action</strong><br>1. O→X ${ch.oToX.length}건 즉시 원복 확인<br>2. 2개월 이상 지속 X ${persistent.length}개 거래관계 우선관리<br>3. Risk P1 ${risks.filter(r=>r.priority==='P1').length}개 집중 Action<br>4. 90% 목표까지 ${needImprove}건 추가 O 전환 필요`;
renderReport(cur,s,ps,ch,risks,worst,mostX,bestImp,needImprove);
bindDynamic(risks,data,cur);
}
function upsertAction(k,field,value){let a=actions.find(x=>x.key===k);if(!a){const [outlet,businessNo]=k.split('|||');a={key:k,outlet,businessNo,history:[]};actions.push(a);}a[field]=value;a.updatedAt=new Date().toISOString();a.history=a.history||[];a.history.unshift({at:a.updatedAt,field,value});a.history=a.history.slice(0,50);saveActions();render();}
function bindDynamic(risks,data,cur){document.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>upsertAction(el.dataset.key,el.dataset.field,el.value));document.querySelectorAll('[data-open]').forEach(btn=>btn.onclick=()=>{const [outlet,biz]=btn.dataset.open.split('|||'),r=risks.find(x=>x.outlet===outlet&&x.businessNo===biz),a=actionFor(r)||{},hist=data.filter(x=>x.outlet===outlet&&x.businessNo===biz).sort((a,b)=>a.month.localeCompare(b.month));$('ctModalTitle').textContent=r.businessName;$('ctModalBody').innerHTML=`<p><b>${esc(outlet)}</b> · ${esc(biz)} · 담당 ${esc(r.manager)}</p><table><thead><tr><th>월</th>${E.map(e=>`<th>${e}</th>`).join('')}</tr></thead><tbody>${hist.map(x=>`<tr><td>${x.month}</td>${E.map(e=>`<td>${L.normStatus(x.statuses[e])||'-'}</td>`).join('')}</tr>`).join('')}</tbody></table><h3>Action</h3><p>상태: <b>${actionStatusLabel(a.status)}</b> · 원인: ${esc(reasons[a.reasonCode]||'미입력')} · Due: ${esc(a.dueDate||'-')}</p><p>${esc(a.plan||'조치계획 미입력')}</p><h3>History</h3><ul class="ct-history">${(a.history||[]).slice(0,12).map(h=>`<li>${new Date(h.at).toLocaleString('ko-KR')} · ${esc(h.field)} → ${esc(h.value)}</li>`).join('')||'<li>기록 없음</li>'}</ul>`;$('ctModal').classList.add('open');};});}
function renderReport(cur,s,ps,ch,risks,worst,mostX,bestImp,needImprove){$('ctReport').innerHTML=`<h1>${cur} DCM 운영 현황</h1><div class="ct-print-kpis"><div>연동률<br><b>${pct(s.rate)}</b></div><div>전월비<br><b>${ps.rate!=null?pp(s.rate-ps.rate):'—'}</b></div><div>미연동 X<br><b>${s.X}</b></div><div>X→O<br><b>${ch.xToO.length}</b></div></div><h2>성과</h2><p>전체 연동률 ${pct(s.rate)}, 개선 ${ch.xToO.length}건, 악화 ${ch.oToX.length}건. ${bestImp?`개선폭 최대 거점 ${esc(bestImp.o)} ${pp(bestImp.delta)}.`:''}</p><h2>Risk</h2><p>${mostX?`미연동 최다 ${esc(mostX.o)} X ${mostX.x}건. `:''}${worst?`연동률 최저 ${esc(worst.o)} ${pct(worst.rate)}. `:''}P1 ${risks.filter(r=>r.priority==='P1').length}개.</p><h2>Next Action</h2><p>O→X 즉시 원복, 장기 X 우선관리, P1 집중 조치, 90% 목표까지 ${needImprove}건 추가 개선.</p><h2>Risk TOP 10</h2><table><thead><tr><th>Priority</th><th>거점</th><th>거래처</th><th>Aging</th><th>Score</th></tr></thead><tbody>${risks.slice(0,10).map(r=>`<tr><td>${r.priority}</td><td>${esc(r.outlet)}</td><td>${esc(r.businessName)}</td><td>${r.streak}M</td><td>${r.score}</td></tr>`).join('')}</tbody></table>`;}
function installUnifiedBackup(){const old=$('backupBtn');if(old){const b=old.cloneNode(true);old.replaceWith(b);b.onclick=()=>{const data=loadData(),blob=new Blob([JSON.stringify({schemaVersion:10,exportedAt:new Date().toISOString(),data,actions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='DCM_dashboard_backup_v10.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};}
const inp=$('backupInput');if(inp){const ni=inp.cloneNode(true);inp.replaceWith(ni);ni.onchange=e=>{const f=e.target.files[0];if(!f)return;const fr=new FileReader();fr.onload=()=>{try{const obj=JSON.parse(fr.result);if(!Array.isArray(obj.data))throw 0;localStorage.setItem(DATA_KEY,JSON.stringify(obj.data));actions=Array.isArray(obj.actions)?obj.actions:[];saveActions();location.reload();}catch(err){alert('올바른 DCM 백업 JSON이 아닙니다.');}};fr.readAsText(f);};}}
function init(){installUnifiedBackup();$('ctPrint').onclick=()=>window.print();$('ctClose').onclick=()=>$('ctModal').classList.remove('open');$('manager').addEventListener('change',()=>setTimeout(render,0));$('outlet').addEventListener('change',()=>setTimeout(render,0));$('month').addEventListener('change',()=>setTimeout(render,0));$('fileInput').addEventListener('change',()=>setTimeout(render,800));$('resetBtn').addEventListener('click',()=>setTimeout(()=>{actions=[];saveActions();render();},0));render();}
window.addEventListener('load',init);
})();