(()=>{
'use strict';
const L=window.DCMLogic,CFG=window.DCM_CONFIG,DATA_KEY='dcm-dashboard-v8-data',ACTION_KEY='dcm-dashboard-v10-actions';
if(!L||!CFG){console.error('[DCM Control Tower] DCMLogic/DCM_CONFIG not loaded');return;}
const E=L.E,$=id=>document.getElementById(id),TARGET=.95;
const reasons={'01':'시스템 미구축','02':'거래처 사용거부','03':'ERP Interface 오류','04':'Master 불일치','05':'신규거래처','06':'공급중단 예정','07':'사용법 미숙','08':'데이터 오류','09':'확인 중','99':'기타'};
let initialized=false;
function clone(x){return JSON.parse(JSON.stringify(x));}
function loadData(){try{const x=JSON.parse(localStorage.getItem(DATA_KEY));if(Array.isArray(x)&&x.length)return x;}catch(e){console.warn('[DCM Control Tower] local data read failed',e);}return clone(window.DCM_BASE_DATA||[]);}
function loadActions(){try{const x=JSON.parse(localStorage.getItem(ACTION_KEY));return Array.isArray(x)?x:[];}catch(e){return [];}}
let actions=loadActions();
function saveActions(){localStorage.setItem(ACTION_KEY,JSON.stringify(actions));}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function pct(v){return v==null?'—':(v*100).toFixed(1)+'%';}
function pp(v){return v==null||!Number.isFinite(v)?'—':`${v>=0?'+':''}${(v*100).toFixed(1)}%p`;}
function key(r){return `${r.outlet}|||${r.businessNo}`;}
function months(data){return [...new Set(data.map(r=>r.month).filter(Boolean))].sort();}
function currentMonth(data){const selected=$('month')?.value;return selected||months(data)[months(data).length-1]||null;}
function selected(data,m){const manager=$('manager')?.value||'전체',outlet=$('outlet')?.value||'전체';return data.filter(r=>r.month===m&&(manager==='전체'||r.manager===manager)&&(outlet==='전체'||r.outlet===outlet));}
function scopeLabel(){return `${$('manager')?.value||'전체'} · ${$('outlet')?.value||'전체'} · ${$('month')?.value||''}`;}
function setText(id,v){const el=$(id);if(el)el.textContent=v;}
function streakRows(data,cur){const ms=months(data).filter(m=>m<=cur),by=new Map();data.filter(r=>ms.includes(r.month)).forEach(r=>{const k=key(r);if(!by.has(k))by.set(k,{});by.get(k)[r.month]=r;});const out=[];by.forEach(hist=>{const r=hist[cur];if(!r)return;const entityStreak={};let max=0;E.forEach(e=>{let n=0;for(let i=ms.length-1;i>=0;i--){if(L.normStatus(hist[ms[i]]?.statuses?.[e])==='X')n++;else break;}entityStreak[e]=n;max=Math.max(max,n);});out.push({...r,streak:max,entityStreak});});return out;}
function riskRows(data,cur,curr,prior,ch){const currentKeys=new Set(curr.map(key)),pmap=new Map(prior.map(r=>[key(r),r])),o2x=new Set(ch.oToX.map(x=>`${x.outlet}|||${x.businessNo}|||${x.entity}`));return streakRows(data,cur).filter(r=>currentKeys.has(key(r))&&E.some(e=>L.normStatus(r.statuses?.[e])==='X')).map(r=>{let score=0,xCount=0,currentXScore=0,persistScore=0,degradeScore=0,newXScore=0;E.forEach(e=>{if(L.normStatus(r.statuses?.[e])!=='X')return;xCount++;score+=2;currentXScore+=2;const st=r.entityStreak[e]||0;if(st>=2){const add=3*Math.min(st-1,3);score+=add;persistScore+=add;}if(o2x.has(`${r.outlet}|||${r.businessNo}|||${e}`)){score+=4;degradeScore+=4;}if(!L.normStatus(pmap.get(key(r))?.statuses?.[e])){score+=2;newXScore+=2;}});return {...r,xCount,score,currentXScore,persistScore,degradeScore,newXScore,priority:score>=12?'P1':score>=7?'P2':'P3'};}).sort((a,b)=>b.score-a.score||b.xCount-a.xCount||String(a.businessName).localeCompare(String(b.businessName),'ko'));}
function actionKey(r){return key(r);}
function actionFor(r){return actions.find(a=>a.key===actionKey(r))||null;}
function statusLabel(s){return ({TODO:'미조치',IN_PROGRESS:'진행중',WAITING:'업체회신',DONE:'완료'})[s]||'미조치';}
function scoreDetail(r){const parts=[];if(r.currentXScore)parts.push(`현재X ${r.currentXScore}`);if(r.persistScore)parts.push(`지속X ${r.persistScore}`);if(r.degradeScore)parts.push(`O→X ${r.degradeScore}`);if(r.newXScore)parts.push(`신규X ${r.newXScore}`);return parts.join(' + ');}
function render(){try{
 const data=loadData(),cur=currentMonth(data);if(!cur){console.warn('[DCM Control Tower] no current month');return;}
 const ms=months(data),idx=ms.indexOf(cur),prev=idx>0?ms[idx-1]:null,curr=selected(data,cur),prior=prev?selected(data,prev):[];
 const s=L.summarize(curr),ps=L.summarize(prior),ch=L.compare(prior,curr),risks=riskRows(data,cur,curr,prior,ch),persistent=risks.filter(r=>r.streak>=2);
 setText('ctRate',pct(s.rate));setText('ctDelta',prev&&ps.rate!=null&&s.rate!=null?pp(s.rate-ps.rate):'—');setText('ctX',s.X.toLocaleString());setText('ctX2O',ch.xToO.length.toLocaleString());setText('ctO2X',ch.oToX.length.toLocaleString());
 const persistentStates=persistent.reduce((n,r)=>n+E.filter(e=>(r.entityStreak[e]||0)>=2).length,0);setText('ctPersist',persistentStates.toLocaleString());
 const aging={m1:0,m2:0,m3:0,m46:0,m6:0};risks.forEach(r=>E.forEach(e=>{const n=r.entityStreak[e]||0;if(n===1)aging.m1++;else if(n===2)aging.m2++;else if(n===3)aging.m3++;else if(n>=4&&n<=6)aging.m46++;else if(n>6)aging.m6++;}));
 [['ctAge1',aging.m1],['ctAge2',aging.m2],['ctAge3',aging.m3],['ctAge46',aging.m46],['ctAge6',aging.m6]].forEach(([id,v])=>setText(id,v.toLocaleString()));
 const gap=s.rate==null?null:Math.max(0,TARGET-s.rate),need=s.evaluated?Math.ceil(Math.max(0,TARGET*s.evaluated-s.O)):0;setText('ctTargetNow',pct(s.rate));setText('ctTargetGap',gap==null?'—':pp(-gap));setText('ctTargetNeed',`${need.toLocaleString()}건`);
 const rb=$('ctRiskBody');if(rb)rb.innerHTML=risks.slice(0,20).map((r,i)=>`<tr><td>${i+1}</td><td><span class="ct-priority ct-${r.priority.toLowerCase()}">${r.priority}</span></td><td>${esc(r.outlet)}</td><td>${esc(r.manager)}</td><td>${esc(r.businessName)}</td><td class="mono">${esc(r.businessNo)}</td><td>${E.map(e=>L.normStatus(r.statuses?.[e])||'-').join(' / ')}</td><td>${r.streak}M</td><td><strong>${r.score}</strong><br><small title="${esc(scoreDetail(r))}">${esc(scoreDetail(r))}</small></td><td><button class="ct-btn" data-open="${esc(key(r))}">Action</button></td></tr>`).join('')||'<tr><td colspan="10" class="empty">현재 필터 범위에 미연동 위험 거래처가 없습니다.</td></tr>';
 const ab=$('ctActionBody');if(ab)ab.innerHTML=risks.slice(0,30).map(r=>{const a=actionFor(r)||{};return `<tr><td><span class="ct-priority ct-${r.priority.toLowerCase()}">${r.priority}</span></td><td>${esc(r.businessName)}</td><td>${esc(r.outlet)}</td><td>${esc(r.manager)}</td><td>${r.streak}M</td><td><select data-field="reasonCode" data-key="${esc(key(r))}"><option value="">원인 선택</option>${Object.entries(reasons).map(([k,v])=>`<option value="${k}" ${a.reasonCode===k?'selected':''}>${k} ${v}</option>`).join('')}</select></td><td><input type="text" data-field="plan" data-key="${esc(key(r))}" value="${esc(a.plan||'')}" placeholder="조치계획"></td><td><input type="date" data-field="dueDate" data-key="${esc(key(r))}" value="${esc(a.dueDate||'')}"></td><td><select data-field="status" data-key="${esc(key(r))}">${['TODO','IN_PROGRESS','WAITING','DONE'].map(x=>`<option value="${x}" ${(a.status||'TODO')===x?'selected':''}>${statusLabel(x)}</option>`).join('')}</select></td></tr>`}).join('')||'<tr><td colspan="9" class="empty">현재 필터 범위에 Action 대상이 없습니다.</td></tr>';
 const riskKeys=new Set(risks.map(key)),used={};actions.filter(a=>riskKeys.has(a.key)).forEach(a=>{if(a.reasonCode)used[a.reasonCode]=(used[a.reasonCode]||0)+1;});const total=Object.values(used).reduce((a,b)=>a+b,0)||1,pareto=$('ctReasonBars');if(pareto)pareto.innerHTML=Object.entries(used).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,v])=>`<div class="ct-bar-row"><span>${esc(reasons[k]||k)}</span><div class="ct-bar"><i style="width:${v/total*100}%"></i></div><b>${v}</b></div>`).join('')||'<div class="ct-note">현재 필터 범위의 Action Board에서 원인코드를 입력하면 자동 집계됩니다.</div>';
 const outlets=[...new Set(curr.map(r=>r.outlet))].map(o=>{const cs=L.summarize(curr.filter(r=>r.outlet===o)),prs=L.summarize(prior.filter(r=>r.outlet===o));return {o,rate:cs.rate,delta:prev&&prs.rate!=null&&cs.rate!=null?cs.rate-prs.rate:null,x:cs.X};});const worst=[...outlets].sort((a,b)=>(a.rate??1)-(b.rate??1))[0],mostX=[...outlets].sort((a,b)=>b.x-a.x)[0],best=[...outlets].filter(x=>x.delta!=null).sort((a,b)=>b.delta-a.delta)[0];
 const ai=$('ctAi');if(ai)ai.innerHTML=`<div class="ct-note">분석 범위: ${esc(scopeLabel())}</div><strong>${cur} 월간 요약</strong><br>• 전체 연동률 <strong>${pct(s.rate)}</strong>${prev&&ps.rate!=null?`, 전월 대비 <strong>${pp(s.rate-ps.rate)}</strong>`:''}<br>• 미연동 X <strong>${s.X.toLocaleString()}건</strong>, X→O 개선 <strong>${ch.xToO.length.toLocaleString()}건</strong>, O→X 악화 <strong>${ch.oToX.length.toLocaleString()}건</strong><br>• ${mostX?`미연동 최다: <strong>${esc(mostX.o)} X ${mostX.x}</strong>`:'거점 데이터 없음'}<br>• ${worst?`연동률 최저: <strong>${esc(worst.o)} ${pct(worst.rate)}</strong>`:''}<br>• ${best?`개선폭 최대: <strong>${esc(best.o)} ${pp(best.delta)}</strong>`:''}<br><br><strong>Recommended Action</strong><br>1. O→X ${ch.oToX.length}건 즉시 원복 확인<br>2. 2개월 이상 지속 X ${persistent.length}개 거래관계 우선관리<br>3. Risk P1 ${risks.filter(r=>r.priority==='P1').length}개 집중 Action<br>4. 95% 목표까지 ${need}건 추가 O 전환 필요`;
 renderReport(cur,s,ps,ch,risks,worst,mostX,best,need);bindDynamic(risks,data);window.DCM_CONTROL_TOWER_OK=true;
 }catch(err){window.DCM_CONTROL_TOWER_OK=false;console.error('[DCM Control Tower] render failed',err);}
}
function upsert(k,field,value){let a=actions.find(x=>x.key===k);if(!a){const [outlet,businessNo]=k.split('|||');a={key:k,outlet,businessNo,history:[]};actions.push(a);}a[field]=value;a.updatedAt=new Date().toISOString();a.history=a.history||[];a.history.unshift({at:a.updatedAt,field,value});a.history=a.history.slice(0,50);saveActions();render();}
function bindDynamic(risks,data){document.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>upsert(el.dataset.key,el.dataset.field,el.value));document.querySelectorAll('[data-open]').forEach(btn=>btn.onclick=()=>{const r=risks.find(x=>key(x)===btn.dataset.open);if(!r)return;const a=actionFor(r)||{},hist=data.filter(x=>key(x)===key(r)).sort((a,b)=>a.month.localeCompare(b.month));setText('ctModalTitle',r.businessName);const body=$('ctModalBody');if(body)body.innerHTML=`<p><b>${esc(r.outlet)}</b> · ${esc(r.businessNo)} · 담당 ${esc(r.manager)}</p><table><thead><tr><th>월</th>${E.map(e=>`<th>${e}</th>`).join('')}</tr></thead><tbody>${hist.map(x=>`<tr><td>${x.month}</td>${E.map(e=>`<td>${L.normStatus(x.statuses?.[e])||'-'}</td>`).join('')}</tr>`).join('')}</tbody></table><h3>Action</h3><p>상태: <b>${statusLabel(a.status)}</b> · 원인: ${esc(reasons[a.reasonCode]||'미입력')} · Due: ${esc(a.dueDate||'-')}</p><p>${esc(a.plan||'조치계획 미입력')}</p><h3>History</h3><ul class="ct-history">${(a.history||[]).slice(0,12).map(h=>`<li>${new Date(h.at).toLocaleString('ko-KR')} · ${esc(h.field)} → ${esc(h.value)}</li>`).join('')||'<li>기록 없음</li>'}</ul>`;$('ctModal')?.classList.add('open');});}
function renderReport(cur,s,ps,ch,risks,worst,mostX,best,need){const r=$('ctReport');if(!r)return;r.innerHTML=`<h1>${cur} DCM 운영 현황</h1><p>범위: ${esc(scopeLabel())}</p><div class="ct-print-kpis"><div>연동률<br><b>${pct(s.rate)}</b></div><div>전월비<br><b>${ps.rate!=null&&s.rate!=null?pp(s.rate-ps.rate):'—'}</b></div><div>미연동 X<br><b>${s.X}</b></div><div>X→O<br><b>${ch.xToO.length}</b></div></div><h2>성과</h2><p>전체 연동률 ${pct(s.rate)}, 개선 ${ch.xToO.length}건, 악화 ${ch.oToX.length}건. ${best?`개선폭 최대 거점 ${esc(best.o)} ${pp(best.delta)}.`:''}</p><h2>Risk</h2><p>${mostX?`미연동 최다 ${esc(mostX.o)} X ${mostX.x}건. `:''}${worst?`연동률 최저 ${esc(worst.o)} ${pct(worst.rate)}. `:''}P1 ${risks.filter(x=>x.priority==='P1').length}개.</p><h2>Next Action</h2><p>O→X 즉시 원복, 장기 X 우선관리, P1 집중 조치, 95% 목표까지 ${need}건 추가 개선.</p>`;}
function installBackup(){const old=$('backupBtn');if(old&&!old.dataset.ctBound){old.dataset.ctBound='1';old.addEventListener('click',e=>{e.stopImmediatePropagation();const blob=new Blob([JSON.stringify({schemaVersion:10,exportedAt:new Date().toISOString(),data:loadData(),actions},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='DCM_dashboard_backup_v10.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);},true);}}
function init(){if(initialized)return;const required=['month','manager','outlet','ctRate','ctAge1','ctTargetNow'];if(required.some(id=>!$(id))){setTimeout(init,50);return;}initialized=true;installBackup();$('ctPrint')?.addEventListener('click',()=>window.print());$('ctClose')?.addEventListener('click',()=>$('ctModal')?.classList.remove('open'));['manager','outlet','month'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(render,0)));$('fileInput')?.addEventListener('change',()=>setTimeout(render,900));render();setTimeout(()=>{if(!window.DCM_CONTROL_TOWER_OK)render();},300);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.addEventListener('load',()=>{init();setTimeout(render,0);},{once:true});
})();